definitions:
  models.Definitions:
    properties:
      images:
        items:
          $ref: '#/definitions/models.image'
        type: array
      texts:
        items:
          $ref: '#/definitions/models.text'
        type: array
    type: object
  models.RequestBody:
    properties:
      definitions:
        $ref: '#/definitions/models.Definitions'
      template:
        type: string
      values:
        $ref: '#/definitions/models.Values'
    type: object
  models.Values:
    properties:
      images:
        items:
          $ref: '#/definitions/models.images'
        type: array
      items:
        items:
          $ref: '#/definitions/models.item'
        type: array
    type: object
  models.image:
    properties:
      height:
        type: integer
      name:
        type: string
      pageNo:
        type: integer
      width:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  models.images:
    properties:
      name:
        type: string
      objectKey:
        type: string
    type: object
  models.item:
    properties:
      fieldName:
        type: string
      value:
        type: string
    type: object
  models.text:
    properties:
      fieldName:
        type: string
      pageNo:
        type: integer
      size:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /addDataToTemplate:
    post:
      consumes:
      - application/json
      description: Add data to template
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add data to template
      tags:
      - Add Data to Template
  /uploadImages:
    post:
      consumes:
      - multipart/form-data
      description: Upload images to S3
      parameters:
      - description: logo
        in: formData
        name: logo
        required: true
        type: file
      - description: seal
        in: formData
        name: seal
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload images to S3
      tags:
      - Upload Images
  /uploadTemplate:
    post:
      consumes:
      - multipart/form-data
      description: Upload template to S3
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload template to S3
      tags:
      - UploadTemplate
swagger: "2.0"
