definitions:
  models.LogoData:
    properties:
      height:
        type: integer
      pageNo:
        type: integer
      width:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  models.RawData:
    properties:
      address:
        $ref: '#/definitions/models.address'
      logoData:
        $ref: '#/definitions/models.LogoData'
      name:
        $ref: '#/definitions/models.name'
      phoneNumber:
        $ref: '#/definitions/models.phoneNumber'
      sealData:
        $ref: '#/definitions/models.SealData'
      template:
        type: integer
      zipAddress:
        $ref: '#/definitions/models.zipAddress'
    required:
    - template
    type: object
  models.SealData:
    properties:
      height:
        type: integer
      pageNo:
        type: integer
      width:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  models.address:
    properties:
      address:
        type: string
      pageNo:
        type: integer
      size:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  models.name:
    properties:
      name:
        type: string
      pageNo:
        type: integer
      size:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  models.phoneNumber:
    properties:
      pageNo:
        type: integer
      phoneNumber:
        type: integer
      size:
        type: integer
      x:
        type: integer
      "y":
        type: integer
    type: object
  models.zipAddress:
    properties:
      pageNo:
        type: integer
      size:
        type: integer
      x:
        type: integer
      "y":
        type: integer
      zipAddress:
        type: integer
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /addData:
    post:
      consumes:
      - multipart/form-data
      description: Create new pdf from scratch
      parameters:
      - in: formData
        name: address
        type: string
      - in: formData
        name: name
        type: string
      - in: formData
        name: phoneNumber
        type: integer
      - in: formData
        name: zipAddress
        type: integer
      - description: products
        in: formData
        items:
          type: string
        name: products
        required: true
        type: array
      - description: logo
        in: formData
        name: logo
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create new pdf from scratch
      tags:
      - GeneratePDF1
  /addToTemplate:
    post:
      consumes:
      - multipart/form-data
      description: Create new pdf with positions
      parameters:
      - description: rawData
        in: body
        name: rawData
        required: true
        schema:
          $ref: '#/definitions/models.RawData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create new pdf with positions
      tags:
      - GeneratePDF
swagger: "2.0"
